### PR TITLE
Export the sprite and return an add function when deleting the sprite.

### PR DESCRIPTION
**Pull request by kchadha**
### Proposed Changes

Towards the 'Restore' functionality for restoring deleted sprites. Export a sprite before deleting it and return a function to add that sprite back.

### Test Coverage

Manual testing.

### Related PRs
LLK/scratch-gui#1438

### CODE REVIEW

**Review by rschamp — APPROVED** [review]
This is so clean!

**Comment by rschamp** [comment]
It would be nice to have tests however

**Comment by kchadha** [comment]
@rschamp, just added an integration test for restoring a deleted sprite. This also uncovered a subtle bug where the restoreFunction returned by the deleteSprite function was not returning the promise of adding the sprite back.

**Comment by rschamp** [comment]
Thank you!

**Review by rschamp — APPROVED** [review]

**Pull request merged**
