### PR TITLE
Clamp ghost effect

### LINKED ISSUE #1875: Ghost effect not clamped to 0 or 100
### Expected Behavior

The actual value of the ghost effect should never be less than 0 or greater than 100 as is the case in 2.0.  Any attempt to set it to a number > 100 should set it to 100.  Similarly, any attempt to set it to a number < 0 should set it to 0.

### Actual Behavior

If you run "Change Ghost Effect by 10" repeatedly, the ghost effect can go above 100.  Similarly you can reduce the ghost effect below 0 by using a negative number.  You can also set the ghost effect directly to a number out of the range with the "Set ghost effect to [ ]" block

### Steps to Reproduce

Create a new project
On the cat build these stacks:
screen shot 2018-12-27 at 9 55 49 am
Press space
Note: the cat fades away
Press b
note: the cat returns
press space twice
Note: the cat fades away
Press b
Note: the cat does not return
press b again
Note: the cat returns.  The value for the ghost effect was 200 so you had to reduce it by 100 twice to get it to appear again.
Drag out and run the block "Set ghost effect to [300]"
Note: the cat disappears
Press space
Note: the cat does not return
Press space twice more
Note: the cat returns.  You successfully set the ghost effect to 300. 

Here's a useful project to test it with: https://scratch.mit.edu/projects/274813682/

### Operating System and Browser

Mac Chrome

### PR DESCRIPTION
**Pull request by apple502j**
### Resolves
Resolves #1875

### Proposed Changes
Clamps ghost effect using MathUtil

### Reason for Changes
It goes more than 100, or less than 0, which is not compatible

### Test Coverage
Use the script in #1875

### CODE REVIEW

**Comment by thisandagain** [comment]
Awesome. Thanks @apple502j! :-)

**Comment by thisandagain** [comment]
@apple502j Do you mind removing the changes to the `package-lock` file from this PR?

**Comment by apple502j** [comment]
@thisandagain Sorry, I don't know how to do that. Should I re-submit PR?

**Comment by thisandagain** [comment]
@apple502j You can undo your commit (`git reset --soft HEAD~1`) and then build back up the commit without the `package-lock` file. Something along the lines of:
```bash
git add src/blocks/scratch3_looks.js
git commit -m "Clamp ghost effect"
git push [myremote] clamp-ghost -f
```

That will update this PR with the new commit.

**Comment by towerofnix** [comment]
I frequently go with these steps, which I believe are to the same effect, but are relatively easier for me to remember:

```
rm package-lock.json
git commit --amend
git push [myremote] clamp-ghost --force
```

**Comment by apple502j** [comment]
Oops, I deleted package-lock - is that okay?

**Comment by thisandagain** [comment]
@apple502j Yup. That's a problem. To land this PR we will need no changes made to the `package-lock`.

**Comment by apple502j** [comment]
I'll close this issue. Someone else, please submit!

**Pull request closed without merging**
