### PR TITLE
Bug - escapeFromConditionalBranches

### PR DESCRIPTION
**Pull request by griffpatch**
Fixes Bug: Execution bug: can't escape from conditional branches that end with a Promise-resolution-terminating command block #464

### CODE REVIEW

**Comment by griffpatch** [comment]
Wait... hold off on that... this is not a good fix as I forgot to account for promises at the end of actual loops. This will break that scenario at present.

**Comment by griffpatch** [comment]
Forgot to say, this fix is ok now and can be looked at (if it helps).
My only hesitation is that it would be nicer if the scripts to exit the current stack frame did not have to live in this bit of the codebase as this is usually done in the stepThread function rather than the execute function... but since the popThread and getNextBlockID was already being done in the later for the isPromise callback I added the other logic to look for end of execution and loop detection in there too to fix the bug.

**Review by thisandagain — APPROVED** [review]
Thanks @griffpatch . This looks good. Sorry for the slow review on this, but I just wanted to make sure to test it thoroughly.

**Comment by griffpatch** [comment]
Very very wise :) I prefer it that way :)

**Pull request merged**
