### PR TITLE
Use new updateCPURenderAttributes in video sensing

### LINKED ISSUE #2541: Video motion value for sprite is always zero until the sprite is interacted
### Expected Behavior
As long as the user accepts video, video motion value is set correctly.

### Actual Behavior
Until the sprite is interacted, motion for the sprite is always 0 and direction is always -1. Values for stage are correct. There is no error on console.

"Interacting" includes:
- dragging, either on editor or on player (by set drag mode)
- clicking the sprite
- using say block, think block or ask block
- changing sprite selection from other sprite to the sprite
- using touching color/object block
- stamping

"Interacting" does not include:
- changing x/y
- changing direction
- changing draggability
- changing rotation style
- changing costume
- changing size
- changing graphic effect
- show/hide
- changing layer
- changing video transparency
- switching video on/off/flipped
- using pen extension (except stamp)

### Steps to Reproduce
1. Make a project using "when video motion > 0" block
2. Save and reload
3. Allow video permission
4. Dance (script not executed)
5. Interact with the sprite (script get executed)

### Operating System and Browser
Firefox 79 Windows 10

[original repro by Blue_Science](https://scratch.mit.edu/discuss/post/4276336/): My browser / operating system: Ubuntu Linux, Firefox 79.0, Flash 32.0 (release 0)

### PR DESCRIPTION
**Pull request by apple502j**
### Resolves
Resolves #2541 

### Proposed Changes
Use new updateCPURenderAttributes in video sensing

### Reason for Changes
Because @adroitwhiz forgot to change after merging LLK/scratch-render#664

### Test Coverage
Updated test

### CODE REVIEW

**Review by adroitwhiz — APPROVED** [review]
Someday we'll stop using these private APIs here....

**Comment by apple502j** [comment]
@ericrosenbaum Can you merge this? There are many more BaG posts...
Per adroitwhiz's review this should be LGTM

**Comment by ericrosenbaum** [comment]
sorry for the delay on this @apple502j - working on it!

**Comment by adroitwhiz** [comment]
To clarify -- https://github.com/LLK/scratch-render/pull/555 was a refactor which didn't break video sensing. It added the `updateCPURenderAttributes` function, which called both `updateMatrix` and `updateSilhouette`.

Video sensing broke when https://github.com/LLK/scratch-render/pull/664 was merged, which moved more logic into `updateCPURenderAttributes`, requiring it to be called before using `isTouching`.

**Comment by apple502j** [comment]
@adroitwhiz okay thanks

**Review by ericrosenbaum — APPROVED** [review]
LGTM!

**Pull request merged**
