### PR TITLE
Fix issue importing some sb2s that were originally sb1s, with baseLayerMd5 property formatted differently.

### LINKED ISSUE #1714: Save the Minifigs project does not load
This version does not load in 3.0:
https://llk.github.io/scratch-gui/develop/#10118726

This version does load- the only change was to add a shape to the background:
https://llk.github.io/scratch-gui/develop/#258472899

cc @kchadha

### PR DESCRIPTION
**Pull request by kchadha**
### Resolves

Resolves #1714 

### Proposed Changes

Fix issue where sb2s originally from sb1s sometimes have baseLayerMd5 formatted incorrectly. See #1714 for more info.

### Test Coverage

Tested loading project mentioned in #1714, both by project ID and by downloading/uploading sb2.

### CODE REVIEW

**Review by paulkaplan — CHANGES_REQUESTED** [review]
As mentioned offline, requesting an integration test for this.

**Comment by kchadha** [comment]
@paulkaplan, added the integration test

**Comment by kchadha** [comment]
@paulkaplan Ping...

**Review by paulkaplan — APPROVED** [review]
LG

**Pull request merged**
