### PR TITLE
Change Color Scheme to Be More Like 2.0

### PR DESCRIPTION
**Pull request by TheBrokenRail**
### Proposed changes

_Changes The Color Scheme To Look More Like 2.0_
### Reason for changes

_So It Looks More Like 2.0._

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
This kind of goes against the design and color scheme that the scratch team is looking to use in scratch 3.0 (https://github.com/LLK/scratch-blocks/wiki/Design) also this pr should be in [scratch-blocks](https://github.com/LLK/scratch-blocks) not scratch-vm.

**Comment by TheBrokenRail** [comment]
No, I don't think it doses it doesn't even change the blocks at all, I love the flat blocks design, this pr just changes the backgrounds and stuff.

**Comment by CosmicWebServices** [comment]
ok

**Comment by mrjacobbloom** [comment]
Yeah I'd leave the design stuff up to the ST. And the VM playground isn't the final design for the editor, it's just what the ST is using to test what everything looks like hooked together.

You could try userstyles to customize the CSS on your end

**Comment by TheBrokenRail** [comment]
No this just changes the backround color of the workspace

**Comment by tmickel** [comment]
We're actively working on the Scratch GUI, including redesigning some aspects. Although these are the colors and formatting for 2.0, they are likely to look different in 3.0. The VM playground is also not necessarily going to look like the Scratch GUI, as it's meant to be a development tool.

**Pull request closed without merging**
