### PR TITLE
Execution order 2

### PR DESCRIPTION
**Pull request by mzgoddard**
### Resolves

Fix https://github.com/LLK/scratch-vm/issues/1053

### Proposed Changes

Builds on top of #1617.

Update execution order from look instructions. 

### Reason for Changes

Draw order is the reverse of execution order. Update the execution order so it matches the draw order and execute new scripts in the reverse direction.

### Test Coverage

New execute integration tests for changing order and if the scripts were already executing or not.

### CODE REVIEW

**Review by kchadha — COMMENTED** [review]
These changes don't seem to resolve the issue in the project mentioned in #1053. The sprites in the project (216001494) should be constantly shuffling which numbers they're saying, but they stay constant e.g. 

2.0 Behavior:

execution_order_2 0

vs. 

3.0 Behavior

execution_order_3 0

**Comment by mzgoddard** [comment]
@kchadha Ah. That project is encountering an extra detail. <del>`_restartThreads` doesn't honor the new sprite order and maintains thread position.</del>

**Comment by mzgoddard** [comment]
Or rather the threads are not allowed to die before restarting.

**Review by kchadha — APPROVED** [review]
Looks good! Thank you for all the tests and the `broadcast and wait` fix.

**Pull request merged**
