### PR TITLE
WIP Fix #255

### LINKED ISSUE #255: Min/max scale doesn't match Scratch 2.0
Currently it's set to 5%/500% respectively.

However, it appears to have been set based on a function of costume width/height:

https://github.com/LLK/scratch-flash/blob/a931df6ab30e34a1cb2d6f7288f99df1c8f7f49b/src/scratch/ScratchSprite.as#L253

To pull that off, I think we'll need to provide costume/width height from the renderer.

### PR DESCRIPTION
**Pull request by CosmicWebServices**

### CODE REVIEW

**Comment by rschamp** [comment]
@CosmicWebServices Please don't open pull requests for WIPs.  If you're going to be adding more commits, an email is sent to everyone watching the repo for every commit you add after you submit the PR, which can become pretty spammy.

After the code is ready to be pulled in, then open your PR with a description of the changes following the template. Thanks!

**Comment by CosmicWebServices** [comment]
OK thanks sorry about that

**Comment by CosmicWebServices** [comment]
OK just finished it @rschamp now it is exactly like it was in Scratch 2

https://github.com/LLK/scratch-flash/blob/a931df6ab30e34a1cb2d6f7288f99df1c8f7f49b/src/scratch/ScratchSprite.as#L253

**Comment by CosmicWebServices** [comment]
Wait I had an issue with github...

**Comment by CosmicWebServices** [comment]
#322

**Pull request closed without merging**
