### PR TITLE
More keys

### PR DESCRIPTION
**Pull request by AmazingMech2418**
### Resolves

https://github.com/LLK/scratch-vm/issues/1892

### Proposed Changes

This adds the sensing of keys shift and backspace.

### Reason for Changes

This will allow projects to use both the backspace key and shift key.

### Test Coverage

No tests have been completed, but this is a simple change.

### CODE REVIEW

**Comment by apple502j** [comment]
Huh. Please make issues and get "help wanted" before submitting PRs.

**Comment by AmazingMech2418** [comment]
@apple502j The issue was already created, although it was not labelled "help wanted". This PR simply resolves that issue.

**Comment by apple502j** [comment]
@amazinigmech2418 That means they don't add it for now.

**Comment by Kenny2github** [comment]
As an outside contributor, do not open pull requests to resolve issues that are not labelled "help wanted", even if it's a simple fix.
There are design implications to any change, especially changes like this, and the Scratch Team has to consider whether to even make the change before bothering to wonder if they are OK with outside contributors making the change.
Please close this pull request, and only reopen it if #1892 becomes help wanted.

**Pull request closed without merging**
