### PR TITLE
Give Sprites Comment Attribute and allow comment duplication

### LINKED ISSUE #3687: Duplicated sprites lose their comments
_Thanks [stmsmarty30](https://scratch.mit.edu/users/stmsmarty30) for [finding this issue](https://scratch.mit.edu/discuss/post/3305071/)!_

### Expected Behavior
When duplicating sprites, comments should be kept

### Actual Behavior
Sprites lose their comments

### Steps to Reproduce
Add a comment on a sprite
Duplicate the sprite
The new sprite doesn't have a comment

### Operating System and Browser
Windows 10 Firefox 63

### PR DESCRIPTION
**Pull request by Victor-Crawshaw**
### Resolves

Resolves https://github.com/scratchfoundation/scratch-gui/issues/3687

### Proposed Changes

Create comment attribute in Sprite, and modify duplicate() method to copy over that comment attribute. Targets now take comments as an argument so that they may be copied over in Rendered Target as well.

https://github.com/user-attachments/assets/2d898f3b-5b68-4220-8447-2f932c24dc8e

### Reason for Changes

Comments should be an attribute in Sprite because if comments want to be duplicated when sprites are duplicated, then it would make sense for them to be part of a sprite, rather than merely part of a target,

### Test Coverage

Added unit test to ensure comments are duplicated along with a sprite, also made sure all other tests still pass.

### CODE REVIEW

**Comment by Victor-Crawshaw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by John-Crawshaw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Victor-Crawshaw** [comment]
recheck

**Comment by John-Crawshaw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by John-Crawshaw** [comment]
recheck

**Comment by John-Crawshaw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by John-Crawshaw** [comment]
recheck

**Pull request closed without merging**
