### PR TITLE
Cast: Easier to understand grammar

### PR DESCRIPTION
**Pull request by nonusx**
* value.substring(0,1) => value.charAt(0)
* Increase color value length judgment

### Resolves

_What Github issue does this resolve (please include link)?_

### Proposed Changes

_Describe what this Pull Request does_

### Reason for Changes

_Explain why these changes should be made_

### Test Coverage

_Please show how you have added tests to cover your changes_

### CODE REVIEW

**Comment by apple502j** [comment]
I'm sure value.length cannot be 7 and 4 at the same time?

**Comment by joker314** [comment]
Thanks for taking the time to file the PR.

I think these checks are actually already made in `colour.js`, using [a regular expression](https://github.com/LLK/scratch-vm/blob/develop/src/util/color.js#L63). `colour.js` performs further checks, such as making sure that all the characters in the hexstring (bar the initial `#`) are valid hexadecimal digits, in addition to making sure that there are either 4 or 7 characters in total.

As such, the length check here isn't quite needed, because if `colour.js` reported an invalid colour, then it is treated as black (see #2356). This would be true with or without this PR, I think.

**Comment by nonusx** [comment]
Thanks

**Comment by nonusx** [comment]
> I'm sure value.length cannot be 7 and 4 at the same time?

Sorry, I wanted to write it as "||".

**Comment by ericrosenbaum** [comment]
I'm going to close this PR, because it does not address a "help wanted" issue. Please have a look at our [contributor guidelines](https://github.com/LLK/scratch-vm/blob/develop/.github/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
