### PR TITLE
Copy events and customState when creating a clone

### PR DESCRIPTION
**Pull request by rasmushaglund**
### Resolves

https://github.com/LLK/scratch-vm/issues/493 and https://github.com/LLK/scratch-vm/issues/481

### Proposed Changes

Copy `_events` and `_customState`

### Reason for Changes

Clones do not inherit pen color

### Test Coverage

None

### CODE REVIEW

**Review by cwillisf — CHANGES_REQUESTED** [review]
Cloning `_customState` is a good idea, but I don't think we should clone `_events`. The two main reasons I feel that way:
1. `_events` is internal, undocumented `EventEmitter` data. In order to reduce the chances of maintenance headaches later on, I'd rather stick to public APIs when possible -- especially when dealing with code that's not part of this repository.
2. It's possible that rendered targets will eventually have events which are not related to the pen, including (possibly) some events that shouldn't be cloned when cloning the target.

This could end up being pretty tricky to fix in a clean way. The first thing that comes to mind is to let individual block packages react to a clone operation. For example, maybe cloning a target fires `EVENT_TARGET_CLONED` and "pen down" registers for that as well as `EVENT_TARGET_MOVED`. The handler for `EVENT_TARGET_CLONED` could effectively run `penDown` on the new clone. To make that easier, the contents of the `penDown` function should probably be pulled out into a new function which can be called by both `penDown` and the new clone event handler.

That's just one way to approach it, though. If you see an easier way that's fine by me :)

**Comment by rasmushaglund** [comment]
Ok sounds like a better approach, I'll give it a shot :)

**Comment by rasmushaglund** [comment]
@cwillisf would it make sense to only clone _customState in order to solve #493 and #481, and then create another issue/improvement for the refactoring of cloning functionality?

**Comment by cwillisf** [comment]
@rasmushaglund that sounds fine to me :)

**Comment by cwillisf** [comment]
On second thought... I like that idea in principle but I'm not sure it's the right way to go. Cloning the custom state will clone the `penDown` flag, but since the event isn't registered the pen won't actually behave like it's down. Even worse, running the "pen down" block won't fix it because of the `if (!penState.penDown)` in the `penDown` function. I suppose #493 and #481 would technically be fixed, but the user-observable behavior is only slightly better.

I'm starting to think that the best approach might *not* involve cloning `_customState` at all but instead letting individual block packages set custom state on a new clone however they want, potentially using the clone source as a reference. I think we should consider having an event which fires after a clone is created (like `EVENT_TARGET_CLONED` as above), and that event should get both the new clone and the original as parameters. This is an approach that @rschamp and I were discussing last week; I had anticipated we'd get to it later but maybe we shouldn't put it off...

**Comment by rasmushaglund** [comment]
Thanks for the explaination @cwillisf. I agree that this probably is the correct way to solve it.

Where can I add the listeners for the cloning event? I can't find any constructors in the blocks, and the other event listeners (for example in the pen block) is created on an action like penDown and penUp. We would need to add the listeners when the block and clones are created. Any pointers?

**Comment by cwillisf** [comment]
@rasmushaglund sorry for the delay in responding on this. You're right - currently there's no good place to attach event listeners like that. Most likely we'll end up adding some sort of initialization function to each "package" of blocks, but I'm not sure we're quite ready to do that yet. We've been talking within the team about how we might implement extensions in Scratch 3.0 and the decisions we make there are likely to influence other changes to the way we package blocks.

So... I guess the options at the moment are:
- Clone `_customState` as part of the cloning operation, technically fixing #481 and #493 but leaving the bug where the pen thinks it's down but the events aren't hooked up.
- Do nothing for now; wait for us to add a block package initialization function. I'm sure you could do this yourself but as it could involve more structural changes I'd prefer it to come from within the team so we can ~argue~discuss within the team how exactly we want it to happen ;)

Either option is fine by me -- you've already helped us quite a bit just by having this conversation!

**Comment by SillyInventor** [comment]
I'd like to add an alternative: Rather than copying the _customState & _events directly, check _customState, and call penDown(), setpencolortonum(), setpenshadeto(), & setpensizeto() for the new clone. Rinse and repeat for all other states.

In general I'm not a fan of enumeration, but it will alleviate the problem of copying future components that shouldn't be and copying undocumented objects.

**Comment by cwillisf** [comment]
@SillyInventor that seems like a reasonable idea, but it still has some of the same problems. Namely, we need a good way to run some pen-specific code at clone time. We could put the code you describe in the clone code directly, but that code shouldn't really "know about" the pen's implementation details.

Really, running some pen-specific code at clone time is the main hurdle with most of the solutions we've discussed on this PR. We'll add a way to do that at some point, but it hasn't yet sifted to the top of the priority list. We're starting to look at extensions and think about "block packages" in more detail, though, so those prototypes and discussions will likely lead to figuring out how we want to fix this.

**Comment by rasmushaglund** [comment]
No worries @cwillisf, the delay coincided with me working on other things. I agree that the structural changes should be decided by the team that collaborate and discuss every day, and have most knowledge of the system. 

I'd prefer to clone _customState to close those bugs and then revisit when the initialization functions (or similar) are in place.

**Comment by rasmushaglund** [comment]
As I described in https://github.com/LLK/scratch-vm/pull/555 I broke the branch, so I had to start a new pull request.

**Pull request closed without merging**
