### PR TITLE
Configure video device with stage video settings

### PR DESCRIPTION
**Pull request by mzgoddard**
### Resolves

Incremental part of #304

### Proposed Changes

Depends on #1016.

- Configure video device with stage video settings
- Update stage video settings in video device command block handles

### Reason for Changes

Extend the video extension and device work https://github.com/LLK/scratch-vm/pull/1016 to use values stored as a change made in https://github.com/LLK/scratch-vm/pull/1014.

### CODE REVIEW

**Comment by mzgoddard** [comment]
This PR depends on #1016 and will be easier to review once its in.

**Comment by mzgoddard** [comment]
Here's a compare between the PRs: https://github.com/gnarf/scratch-vm/compare/io-video...mzgoddard:target-video-state

**Review by rschamp — APPROVED** [review]
This makes sense to me but @ericrosenbaum should take a look too since he's been doing a lot with this kind of extension state management.

**Comment by mzgoddard** [comment]
Rebased on develop after #1016 was merged. You can see the changes this PR makes now in Files Changed @ericrosenbaum

**Comment by kchadha** [comment]
@mzgoddard, you might need to rebase off of develop again, since the rendered target hyphen/underscore issue should be already addressed there. Sorry for all of the confusion with that.

**Review by ericrosenbaum — APPROVED** [review]
LGTM, pending the issue @kchadha mentioned with-the-hyphen-that-I-added-sorry-again-about-that-oops

**Comment by thisandagain** [comment]
@mzgoddard One more rebase and this should be good to go.

**Comment by thisandagain** [comment]
@kchadha @ericrosenbaum Can one of you take responsibility for resolving the conflict and merging this before our smoke tests this afternoon?

**Comment by kchadha** [comment]
Talked it over with @paulkaplan, and it seems there's no point in doing a merge from develop just to merge this back in, so will try to just merge.

**Pull request merged**
