### PR TITLE
Fix #2086 by resolving pending promise even when power set to 0%

### LINKED ISSUE #2086: BOOST extension: behavior of "rotations" block for 0% power?
We should consider what the desired behavior is for the "turn motor A for 1 rotations" block, in the case where the motor power has been set at or close to 0%, which will prevent the motor from completing the rotation. 

This may be solved by our solution to https://github.com/LLK/scratch-vm/issues/2085

### PR DESCRIPTION
**Pull request by knandersen**
Resolves #2086: rotation-based motor-commands hang when power set to 0%

### CODE REVIEW

**Comment by evhan55** [comment]
Hi, I am testing this again in the new PR and finding a small issue I had seen before in the old PR but wasn't able to reproduce.  I am able to reproduce it now:

1. `set motor A power to 100%`
2. `turn motor A for 1 rotations`
3. `set motor A power to 1%`
4. `turn motor A for 1 rotations`

**Expected**: motor slow moves one rotation
**Actual**: motor moves slowly, stalls for a second, and then finishes the rotation slowly

I get the stalling to happen pretty reliably with those steps above

**Comment by knandersen** [comment]
> Hi, I am testing this again in the new PR and finding a small issue I had seen before in the old PR but wasn't able to reproduce. I am able to reproduce it now:
> 
> 1. `set motor A power to 100%`
> 2. `turn motor A for 1 rotations`
> 3. `set motor A power to 1%`
> 4. `turn motor A for 1 rotations`
> 
> **Expected**: motor slow moves one rotation
> **Actual**: motor moves slowly, stalls for a second, and then finishes the rotation slowly
> 
> I get the stalling to happen pretty reliably with those steps above

Thanks so much for catching this @evhan55. It seems like I keep moving back and forth between two problems. I've described it in a commit for a related PR/issue: https://github.com/LLK/scratch-vm/pull/2100/commits/ecbbacd4c099a4c018b50b510e34cbf53a07b9cd

**Comment by evhan55** [comment]
@knandersen Ah, interesting!  Seems like a tricky dilemma!
Might be worth showing to Eric and Andrew, et. al.

**Comment by evhan55** [comment]
Looks like the performance issue I am seeing will be addressed in a future issue: https://github.com/LLK/scratch-vm/issues/2104.  So, this seems good to land for now!

**Comment by evhan55** [comment]
Okay just tested with the very latest commits again, all looks good and power 0% doesn't make rotation block hang.  Possible performance issues to be addressed later: https://github.com/LLK/scratch-vm/issues/2104.

**Review by evhan55 — APPROVED** [review]
LGTM!

**Pull request merged**
