### PR TITLE
setTimeout to setInterval in Wait Block

### PR DESCRIPTION
**Pull request by AmazingMech2418**
### Resolves

https://github.com/LLK/scratch-vm/issues/1010

#### NOTE:
Other blocks that use setTimeout for a wait feature will have to have a similar change to the wait block in this PR.

### Proposed Changes

Change the definition for the wait block to setInterval().

### Reason for Changes

This will allow for a program to wait more than a certain number of seconds.

### Test Coverage

I unfortunately couldn't test it.

### CODE REVIEW

**Comment by AmazingMech2418** [comment]
The errors are all node modules that aren't present since they can only be found in gh-pages and not develop.

**Comment by AmazingMech2418** [comment]
I tested the code in the console to replace the setTimeout and it works!

**Comment by AmazingMech2418** [comment]
I found the sources of the errors! 
info
This can be found at https://travis-ci.org/LLK/scratch-vm/requests .

**Comment by ericrosenbaum** [comment]
Sorry @amazinigmech2418- we will need to close this one. See https://github.com/LLK/scratch-vm/issues/1010#issuecomment-380841551

**Pull request closed without merging**
